# Generated by Django 4.2.7 on 2023-11-22 07:27

from django.db import migrations, models
import expense_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(null=True, upload_to=expense_tracker.models.user_directory_path),
        ),
    ]
