# Generated by Django 4.2.7 on 2023-11-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='content',
            new_name='name',
        ),
    ]
